// File: scrambler.v
// Generated by MyHDL 0.11
// Date: Sat Apr 29 14:49:30 2023


`timescale 1ns/10ps

module scrambler (
    Clock,
    Reset,
    Input,
    Output
);


input Clock;
input Reset;
input Input;
output Output;
wire Output;

wire feedback;
reg [6:0] state;



always @(posedge Clock, negedge Reset) begin: SCRAMBLER_SEQ
    if ((!Reset)) begin
        state <= 127;
    end
    else begin
        state[7-1:5] <= state[6-1:4];
        state[4-1:1] <= state[3-1:1];
        state[0] <= feedback;
    end
end



assign feedback = (state[6] ^ state[3]);



assign Output = (Input ^ feedback);

endmodule
