// File: encoder.v
// Generated by MyHDL 0.11
// Date: Sat Apr 29 15:14:28 2023


`timescale 1ns/10ps

module encoder (
    Clock,
    Reset,
    Input,
    Output
);


input Clock;
input Reset;
input Input;
output Output;
wire Output;

reg is_odd;
reg [6:0] state;



always @(posedge Clock, negedge Reset) begin: ENCODER_SEQ
    if ((!Reset)) begin
        state <= 0;
        is_odd <= 0;
    end
    else begin
        state[6-1:0] <= state[6-1:0];
        state[6] <= Input;
        is_odd <= 1;
    end
end



assign Output = is_odd ? ((((state[1] ^ state[3]) ^ state[4]) ^ state[6]) ^ state[7]) : ((((state[1] ^ state[2]) ^ state[3]) ^ state[4]) ^ state[7]);

endmodule
